name: Update Text File

on:
  schedule:
    - cron: '27 4 * * *'  # Run daily at 10:00 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add or Delete Text File
        run: |
          echo "This is a simple text file." > example.txt  # Create or overwrite the text file
          # echo "" > example.txt  # Use this line to delete the contents of the text file

      - name: Commit and Push
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add example.txt
          git commit -m "Update example.txt"
          git push https://github.com/${{ secrets.MY_ACCESS_TOKEN }} HEAD:${{ github.ref }} --quiet --set-upstream
